# Generated by Django 3.0.6 on 2020-06-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dealer',
        ),
    ]
